### ISSUE TITLE
Unhandled SQL Error on Ads

### ISSUE THREAD

**Issue by RexfelisLOC** [AdsJumbo/AdsJumbo.com#10]
No ads are being displayed.  In place of the ad there is an "Unhandled SQL Error: too many connections".

**Comment by pubtom** [comment]
I have seen the same "Unhandled SQL Error: too many connections" on banner ads yesterday,

**Comment by gamecells** [comment]
Hello,

Thanks for the reporting an issue. There was a short outage from our server side provider CloudFlare, it should be fixed already.

If the problem occurs again, write to us immediately at: info@adsjumbo.com

Regards,
AdsJumbo Team
