### ISSUE TITLE
Banner ads: Does not fit completly in the Width / Height Properties

### ISSUE THREAD

**Issue by TiMeJuMp** [AdsJumbo/AdsJumbo.com#11]
Hi, your ads do net fit into the width / height property like the ones i know from Microsoft Ad Platform. 
You use also Taboola and Outbrain ads, but they are wrong scaled. 
I used 300x600 and 350x50 Adbanner but both Banner look very ugly cause of wrong scaled ads. 

Any plans for this? I can also give you some example images if you need. 
Thanks Christian

**Comment by adjumbo** [comment]
Hello,

Banner ads have already adjusted the alignment (for 300x600, 320x50, sometimes can be truncated according available ad slot).

If you have any other issues, please let us know at: info@adsjumbo.com

Regards,
AdsJumbo Team
