### ISSUE TITLE
Issues with SDK on Xbox consoles

### ISSUE THREAD

**Issue by TiMeJuMp** [AdsJumbo/AdsJumbo.com#12]
Has anyone else problems with Adsjumbo on Xbox consoles? Since i upgraded my apps with adsjumbo, my error shut down raised very high... Don't know what to do. MS Devportal gives me only "unknown error" as message. 

Thanks for any help.

**Comment by TiMeJuMp** [comment]
So I experimented around and found an error on AppStart with the Chakra.dll When I start my application in the debugger, this is the first error I get. So far no ads are loaded. 

![image](https://user-images.githubusercontent.com/6890804/84744614-c8bc1e80-afb3-11ea-949b-8b709570462f.png)
After I continue, the ads load, but I get a C++ JavaScript error every 5 seconds. (In Debug Window) 

Exception raised at 0x00007FF82358A799 in {AppName}.exe: Microsoft C++ exception: Js::JavascriptException raised at location 0x00000078A9DFE340.

On AdReload much more exceptions are raised.  > 30 Exceptions for 2 banner ads.

But if I remove your SDK and the ads. Such errors do not appear. 

Please give it a check. I don't know how to handle this.

**Comment by RexfelisLOC** [comment]
Same, our crash rate has increased quite a bit since implementing the SDK.

**Comment by adjumbo** [comment]
Hello,

Thanks for reaching out.

As for memory consumption, yes, we have already handled that issue. From our side it seems that webview control consumes more memory than usual.
We would like to solve that problem. From our side it is possible to create new ad codes for you and find an issue. (maybe demand, maybe issue with webview, maybe JS file which causing memory consumption). Some ads from our demand are fully HTML5 compatible (interactive ads - same as from Microsoft SDK), this can sometimes increase a memory consumption. We apologize for that issue. Still working on new hotfix. If there is any issue, please reach us via mail with more details with screenshots scenario.

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
