### ISSUE TITLE
Bug: Interstitial Ads to big on Xbox Apps

### ISSUE THREAD

**Issue by TiMeJuMp** [AdsJumbo/AdsJumbo.com#13]
It is not possible to close the Interstitial Ad on Xbox console App (UWP) the close button is out of window. Please fix.

**Comment by adjumbo** [comment]
Hello,

The close button was fixed. The margin / padding from the right corner of screen has been increased, that the user can close the interstitial unit even on smaller screen sizes.

If you have any other issues, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
