### ISSUE TITLE
BannerAd in a GridViewItem

### ISSUE THREAD

**Issue by fetisenko** [AdsJumbo/AdsJumbo.com#14]
I'm trying to put a BannerAd into a GridView, but it's not clickable in this case.
Here is my gridview code:
`<GridView IsItemClickEnabled="True">
            <GridViewItem Padding="100">
                <adsjumbo:BannerAd 
                   ApplicationId='xxxxxxxxx'
                   WidthAd='300'
                   HeightAd='250'
                   Position='Center' />
            </GridViewItem>
        </GridView>`
But after modifying a default style `<Style TargetType="GridViewItem" x:Key="GridViewItemRevealStyle">` and setting `PointerOverBackground="{x:Null}"` in it,
BannerAd became clickable.
Looks like there is some conflict between your BannerAd and a default PointerOverBackground in a GridViewItem.
There is no such problem with a ListView.

Target version: Windows 10, version 1903.

**Comment by adjumbo** [comment]
Hello,

Thanks for reaching out.

For mentioned event IsItemClickEnabled should be disabled on GridViewItem. In this case, We recommend using another XAML element to track click on ad unit. BannerAd should not be affected.
At the same time, we will look at this issue.

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
