### ISSUE TITLE
Better integration with Unity

### ISSUE THREAD

**Issue by Big3Software** [AdsJumbo/AdsJumbo.com#15]
It would be great if the integration in Unity could be improved.

I've tried a lot of things, but I haven't been able to control the advertising out of the game yet.
For example, I would like to display an interstitial ad at the end of a level in my game. But I haven't found anything how to do that.

Is that possible? If so, are there any examples?

Thanks a lot.

**Comment by adjumbo** [comment]
Hello,

Thanks for reaching out.

Unity3D is specific with implementation directly with any external SDKs. Better usage is call our SDK from the event in Unity3D. 
We understand that this is a cumbersome solution, but when our SDK is directly in Unity3D then may be a problem with the DLLs.

Please refer to: https://github.com/AdsJumbo/AdsJumbo.com
https://unity3d.com/partners/microsoft/porting-guides

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
