### ISSUE TITLE
WinJS SDK Slows app to a hault

### ISSUE THREAD

**Issue by spitfire1337** [AdsJumbo/AdsJumbo.com#16]
Having just one ad displayed will cause my WinJS app to slow to almost a complete halt after a few minutes of the app running. Removing the ad and the issue disappears.

**Comment by adjumbo** [comment]
Hello,

Thanks for reaching out.

As for memory consumption, yes, we have already handled that issue. From our side it seems that webview control consumes more memory than usual.
We would like to solve that problem. From our side it is possible to create new ad codes for you and find an issue. (maybe demand, maybe issue with webview, maybe JS file which causing memory consumption). Some ads from our demand are fully HTML5 compatible (interactive ads - same as from Microsoft SDK), this can sometimes increase a memory consumption. We apologize for that issue. Still working on new hotfix.

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
