### ISSUE TITLE
SDK Needs Stop Method

### ISSUE THREAD

**Issue by RexfelisLOC** [AdsJumbo/AdsJumbo.com#17]
Requesting a method to stop serving ads in the event users purchase ad removal.

**Comment by KuznetsovVN** [comment]
As a workaround, you can use the 'UIElement.Visibility' property, as shown below:

``` XAML
<adsjumbo:BannerAd x:Name="adJumbo1" Visibility="Collapsed" ApplicationId="<APP_ID>" />
```

``` CS
var isUserBoughtAdRemoval = false;
adJumbo1.Visibility = isUserBoughtAdRemoval
  ? Windows.UI.Xaml.Visibility.Collapsed
  : Windows.UI.Xaml.Visibility.Visible;
```

But a more optimal approach is to [dynamically add an advertising banner](https://github.com/AdsJumbo/AdsJumbo.com#if-you-want-to-add-programmatically) in accordance with in-game conditions.

**Comment by adjumbo** [comment]
Hello,

There are two options, either change the vibility via property: Visibility.Collapsed
or remove ad unit programmatically from Gridview, for example x:Name="MyGrid" - remove programmatically.

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
