### ISSUE TITLE
Native SDK is not usable because of missing x64 and ARM runtimes

### ISSUE THREAD

**Issue by jaladaGmbH** [AdsJumbo/AdsJumbo.com#18]
Download the native AdsJumbo example from this repository. Open AdsJumbo_Example_Native.sln and create the app for x64.

`1>Done building project "AdsJumbo_Example_Native.vcxproj" -- FAILED.
1>
1>Build FAILED.
1>
1>MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4365,5): error MSB3030: Could not copy the file "E:\sources\winrt\temp\AdsJumbo.com-master\AdsJumbo_Native_Example\packages\AdsJumbo.Native.1.0.0\build\native\..\..\runtimes\win10-x64\native\AdsJumbo\AdsJumbo.dll" because it was not found.
1>MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4365,5): error MSB3030: Could not copy the file "AdsJumbo.com-master\AdsJumbo_Native_Example\packages\AdsJumbo.Native.1.0.0\build\native\..\..\runtimes\win10-x64\native\AdsJumbo\AdsJumbo.pri" because it was not found.
1>    0 Warning(s)
1>    2 Error(s)
1>
1>Time Elapsed 00:00:01.41
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`  

or for ARM

`1>Done building project "AdsJumbo_Example_Native.vcxproj" -- FAILED.
1>
1>Build FAILED.
1>
1>MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4365,5): error MSB3030: Could not copy the file "AdsJumbo.com-master\AdsJumbo_Native_Example\packages\AdsJumbo.Native.1.0.0\build\native\..\..\runtimes\win10-ARM\native\AdsJumbo\AdsJumbo.dll" because it was not found.
1>MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4365,5): error MSB3030: Could not copy the file "AdsJumbo.com-master\AdsJumbo_Native_Example\packages\AdsJumbo.Native.1.0.0\build\native\..\..\runtimes\win10-ARM\native\AdsJumbo\AdsJumbo.pri" because it was not found.
1>    0 Warning(s)
1>    2 Error(s)
1>
1>Time Elapsed 00:00:12.40
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by Big3Software** [comment]
Yes, 64 bit and ARM binaries should be provided.

**Comment by reconco** [comment]
I sent an E-mail 1 month ago about this. But still, they aren't updated.

**Comment by adjumbo** [comment]
Hello,

Today was added support for C++ architecture x64 and ARM. Please install latest NuGet AdsJumbo.Native version 1.2.0

If you have any other issues, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
