### ISSUE TITLE
UWP - Banner Ads Increases the Process memory

### ISSUE THREAD

**Issue by siddh1004** [AdsJumbo/AdsJumbo.com#19]
On showing the banner ads, the process memory usage went too high just after couple of seconds. After removing the ads from the app everything went to normal.
OS : UWP
Nuget : AdsJumbo 5.9.1

**Comment by adjumbo** [comment]
Hello,

Thanks for reaching out.

As for memory consumption, yes, we have already handled that issue. From our side it seems that webview control consumes more memory than usual.
We would like to solve that problem. From our side it is possible to create new ad codes for you and find an issue. (maybe demand, maybe issue with webview, maybe JS file which causing memory consumption). Some ads from our demand are fully HTML5 compatible (interactive ads - same as from Microsoft SDK), this can be sometimes issue with memory consumption. We apologize for the issue, and still working on new hotfix.

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
