### ISSUE TITLE
Why is it not possible to get the state of readiness of interstitial advertising?

### ISSUE THREAD

**Issue by KuznetsovVN** [AdsJumbo/AdsJumbo.com#20]
The main scenario for using this ad is to show between levels of the game or for some kind of in-game reward.
To fulfill these conditions, I need to know the state of readiness for display.

Currently, there is only one ShowInterstitialAd method that works like a black box, or it will be displayed or not displayed.
In addition, it also has a delay of about 3 seconds, which looks like a hang, which will certainly enrage users.

I'm just sure that the ability to preload ads in the background and display them without delay is a "must be feature".

**Comment by Big3Software** [comment]
I totally agree. Other ad networks have some kind of "requestad" method that calls an event, if an ad is available and ready to show. This will load the ad in the background. The "showad" method should show the ad instantly.

**Comment by adjumbo** [comment]
Hello,

Thanks for reaching out.

The timer interval is set to 2 seconds, before is interstitial ad visible. Meanwhile, ads are cached and displayed. Don't worry, in 99% is available full demand. Black screen is not expected. If there is any issue, please reach us via mail with more details about issue or screenshots scenario.

If you have any other issues or any feedback, please let us know at: info@adsjumbo.com

Kind Regards,
AdsJumbo Team
