### ISSUE TITLE
WinJS SDK is not valid Javascript?

### ISSUE THREAD

**Issue by Game-Unity** [AdsJumbo/AdsJumbo.com#25]
I was trying to import the WinJS SDK which I got send via E-Mail in my Electron App (I do not use Visual Studio), but it totally breaks all my other jQuery for some reason. As I looked up the SDK file, I noticed it isn't valid Javascript code there are ";" missing and some other stuff doesn't make sense. 

Is this SDK written in Javascript or is it another language or some weird compiled stuff? I really need some help here...

**I included the file via a script tag:** 
`<script type="text/javascript" src="./plugins/adsjumbo/sdk.js" ></script>`

_* But the ads seem to load still_

**Comment by adjumbo** [comment]
Hello, Our SDK for WinJS is encrypted to protect a code and SDK. We highly recommend convert the app to pure WinJS or with Electron, you can debug a app with console and via web console.
If there is any additional issue, please send us screenshots to: info@adsjumbo.com, then our team can track the issue.
Best Regards, AdsJumbo.com Team
