### ISSUE TITLE
Cannot install nuget package

### ISSUE THREAD

**Issue by Big3Software** [AdsJumbo/AdsJumbo.com#3]
Attempting to gather dependency information for package 'AdsJumbo.5.5.5' with respect to project 'xxxxxxx', targeting 'native,Version=v0.0'
Gathering dependency information took 13,62 ms
Attempting to resolve dependencies for package 'AdsJumbo.5.5.5' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'AdsJumbo.5.5.5'
Resolved actions to install package 'AdsJumbo.5.5.5'
  GET https://api.nuget.org/v3-flatcontainer/adsjumbo/5.5.5/adsjumbo.5.5.5.nupkg
Install failed. Rolling back...
Package 'Newtonsoft.Json.9.0.1' does not exist in project 'Blox'
Package 'Newtonsoft.Json.9.0.1' does not exist in folder 'xxxxxxxx\packages'
Executing nuget actions took 167,28 ms
Could not install package 'Newtonsoft.Json 9.0.1'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:00.3717060
========== Finished ==========

**Comment by AdsJumbo** [comment]
Hi,

Our NuGet package is compatible yet with Visual Studio projects on XAML and C#. This may be because you want to install the package on C ++ (native platform). Can you confirm it?

C++ and WinJS NuGet package will be available soon.
Otherwise please write us at: info@adsjumbo.com

Any feedback is welcome!

Best Regards,
AdsJumbo Team

**Comment by Big3Software** [comment]
We are using Unity 2019.3.5f1 and IL2CPP, so yes, this is c++.

The .Net Scripting Backend for Windows UWP with C# was deprecated by Unity for 2018.1, see
https://forum.unity.com/threads/deprecation-of-support-for-the-net-scripting-backend-used-by-the-universal-windows-platform.539685/

**Comment by gamecells** [comment]
Hi,

C++ and WinJS NuGet package is in development yet.
As for Unity 2019.3.5f1 and IL2CPP - this will need our winmd package for c ++
Otherwise please reach us at: info@adsjumbo.com

Any feedback is welcome.

Best Regards,
AdsJumbo Team
