### ISSUE TITLE
Using AdsJumbo in Flutter Project

### ISSUE THREAD

**Issue by sarankumar-ns** [AdsJumbo/AdsJumbo.com#30]
Is there any way to use AdsJumbo in Flutter?

I know that we can call C functions using Dart FFI. But, don't tried that.

Any practical example will be helpful.

If you guys build dart plugin then it will be more useful.

**Comment by DomingoMG** [comment]
Is something known?

**Comment by tahercoolguy** [comment]
@DomingoMG have you got any solution for flutter..

**Comment by DomingoMG** [comment]
@tahercoolguy I have contacted Ads Jumbo via email, but their response has been that they will work on a solution with their team of developers.

I am currently unable to use Ads on desktop, I have not been able to find any solution.
