### ISSUE TITLE
For WinForm / WPF apps & games on wpf not working yet

### ISSUE THREAD

**Issue by LyVanBong** [AdsJumbo/AdsJumbo.com#31]
For WinForm / WPF apps & games on wpf not working yet

**Comment by AscendantWare** [comment]
Hi LyVanBong,

you are right!
If you got a WPF-App with a .NET Framework then it will work. If you have a .NET CORE App, then not.
I wrote on 14 April 2021 to the AdsJumbo-Support Team about that to include at least that in the documentation. but still nothing happend.

Here is a example to make it run on WPF .NET Framework:

`xmlns:ads="clr-namespace:AdsJumboWinForm;assembly=AdsJumboWinForm"`
`        <WindowsFormsHost Name="MainFormHost">
            <ads:BannerAds Name="MainBanner"/>
        </WindowsFormsHost>`

`((BannerAds)MainFormHost.Child).ShowAd(728, 90, "emidw63tf2nj");`

**Comment by LyVanBong** [comment]
thank you
