### ISSUE TITLE
Readme instructions for WPF not working

### ISSUE THREAD

**Issue by gileli121** [AdsJumbo/AdsJumbo.com#32]
Hi, I try to test your SDK in the project I have.
For this, I installed the NuGet https://www.nuget.org/packages/AdsJumbo.WinForm.WPF/ 
As suggested in the readme

Then, I followed the instructions in 
https://github.com/AdsJumbo/AdsJumbo.com#step-2-add-xaml-code
When I put `xmlns:adsjumbo="using:AdsJumbo"` in the window, I get this error:
![image](https://user-images.githubusercontent.com/17680514/140608111-b1f06528-0d3e-4c7d-9416-1fde99ffef9e.png)

Is this SDK even tested?

**Comment by gileli121** [comment]
Update:
I found that the instructions here helped:
https://github.com/AdsJumbo/AdsJumbo.com/issues/31#issuecomment-927728228

But I don't see any ads yet:
![image](https://user-images.githubusercontent.com/17680514/140608617-423de612-5eab-40ac-9aef-9488e888885a.png)

For code:
```xaml
<Window x:Class="WindowTop.Window2"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ads="clr-namespace:AdsJumboWinForm;assembly=AdsJumboWinForm"
        xmlns:local="clr-namespace:WindowTop"
        mc:Ignorable="d"
        Title="Window2" Height="450" Width="800">

    <StackPanel>
        <WindowsFormsHost Name="MainFormHost" Background="Red" VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
            <ads:BannerAds ApplicationId="your_app_id"
                               WidthAd="160" 
                               HeightAd="600"/>

        </WindowsFormsHost>
    </StackPanel>
</Window>
```

I also tried to set the app id and I got the same result.
Is it because the app has not been approved yet?
If so, how can I test it? I need it to work in order to test it while developing it.

Thank you

**Comment by c00012** [comment]
I've got a same problem and I e-mailed to AdsJumbo. but they didn't show any solution for wpf app.
