### ISSUE TITLE
Please add .net 6 support for WinUI 3 apps

### ISSUE THREAD

**Issue by Delaire** [AdsJumbo/AdsJumbo.com#34]
Please add .net 6 support for WinUI 3 apps

**Comment by uacaman** [comment]
that would be nice!

**Comment by Qws** [comment]
And MAUI please...

**Comment by pwisk** [comment]
I'm also waiting for support for .NET MAUI. That would be the only option at the moment. I would even be happy with banners only.

**Comment by Delaire** [comment]
Does this mean that you support WinUI 3? I am not seeing the PR linked to this fix.
