### ISSUE TITLE
AdsJumbo weird behavior

### ISSUE THREAD

**Issue by rafak360** [AdsJumbo/AdsJumbo.com#36]
***1º issue:***
I have a `WinForms .NET Framework 4.6.2` application with `AdsJumbo` (version 1.5.0) implemented, I've noticed that when an ADS is clicked it opens up a built-in `Internet Explorer` instead of the default browser set by the user.
Is there a way to change that behavior? I know that in some cases when the user's default browser is an old `Internet Explorer` so the built-in `Internet Explorer` comes in handy however most users have `Chrome` and `Edge` nowadays.
I want it to open up on the user's default browser, is there a workaround for this?

P.S. I noticed that for some ADS it displays a message telling they should update their browsers instead of displaying the actual ADS which is bad for the campaign of the advertiser.

***2º issue:***
Taking into account the same project settings mentioned above, there's also another issue regarding the `closeButton` when showing an ADS by `ShowInterstitialAd(String ApplicationId)`, well if the `Form` is maximized the `closeButton` shows up at the upper corner however if the user restore the `Form` size by clicking on the maximize button again, then the next time `ShowInterstitialAd` is executed the `closeButton` will be at the same position from last time which makes not visible to the user hence forcing the user to click on the maximize button again to be able to see the `closeButton` at the upper corner of the `Form`. So `closeButton` should update its position when the `Form` changes its size when user clicks on the maximize button.

**Comment by Leo-23333** [comment]
Adsjumbo essentially uses Winform's Webbrowser to display ads, so when you click on an AD, you open Internet Explorer, which has stopped updating at the moment, and many computers don't have Internet Explorer anymore, and on these computers, you can't click on ads, so I send an email to Adsjumbo, No reply so far...

**Comment by Dan-Banfield** [comment]
> Adsjumbo essentially uses Winform's Webbrowser to display ads, so when you click on an AD, you open Internet Explorer, which has stopped updating at the moment, and many computers don't have Internet Explorer anymore, and on these computers, you can't click on ads, so I send an email to Adsjumbo, No reply so far...

Don't quote me on this, but I don't think AdsJumbo function as a company anymore. There don't seem to be any signs of life anywhere.

**Comment by Leo-23333** [comment]
> > Adsjumbo essentially uses Winform's Webbrowser to display ads, so when you click on an AD, you open Internet Explorer, which has stopped updating at the moment, and many computers don't have Internet Explorer anymore, and on these computers, you can't click on ads, so I send an email to Adsjumbo, No reply so far...
> 
> Don't quote me on this, but I don't think AdsJumbo function as a company anymore. There don't seem to be any signs of life anywhere.

If this company is really dead, it is really bad, it still has more than $1000 of advertising fees to pay me, if you know more information, please let me know, thank you
