### ISSUE TITLE
Please add .net 6 support for WinUI 3 apps

### ISSUE THREAD

**Issue by Delaire** [AdsJumbo/AdsJumbo.com#37]
Please add .net 6 support for WinUI 3 apps

https://github.com/AdsJumbo/AdsJumbo.com/issues/34 this issue was closed but not fixed.

**Comment by adjumbo** [comment]
Hi, His is not qualified as an issue. This is unsupported SDK from our side for WinUI 3 apps. Kind Regards, AdsJumbo Team
