### ISSUE TITLE
WinJS version of SDK

### ISSUE THREAD

**Issue by creakosta** [AdsJumbo/AdsJumbo.com#5]
Hello! When WinJS version of SDK is released?

**Comment by spitfire1337** [comment]
I second this, their nuget package states the sdk supports HTML5 apps but all I see is reference to Xaml

**Comment by adjumbo** [comment]
Hello,

Now the SDK is now available for WinJS / HTML5 apps and games, contact us and we will provide you the SDK link and implementation guide.

If you have any other issues, please let us know at: info@adsjumbo.com

Regards,
AdsJumbo Team
