### ISSUE TITLE
FedEx ad pops up browser without user input

### ISSUE THREAD

**Issue by GameFaceLLC** [AdsJumbo/AdsJumbo.com#6]
The FedEx ad is popping up an Edge browser without user input.

**Comment by gamecells** [comment]
Hello,

Thank you for your feedback.

We'll definitely check it. It shouldn't do that - an FedEx ad should open after user input, if any.
Otherwise you can reach us at mail: info@adsjumbo.com

Any feedback is welcome!

Regards,
AdsJumbo.com Team
