### ISSUE TITLE
Interstitial .ShowInterstitialAd() should return some info

### ISSUE THREAD

**Issue by pubtom** [AdsJumbo/AdsJumbo.com#7]
Interstitial .ShowInterstitialAd() should return some info like: AdDisplaySuccess, NoAdAvailable, AdDisplayError, etc.

Also could you please add NewAdReady, AdDisplayed Events to Intertitial Ads?

After .ShowInterstitialAd() called I would like to have an info that the interstitial ad displayed or not.
I would like to display interstitial ad when it is ready.

**Comment by adjumbo** [comment]
Hello,

Please check the latest NuGet package, all of these events are now available, including programatically.

The info is returned via events on the ad unit (pertains banner ads, interstitial ads).

If you have any other issues, please let us know at: info@adsjumbo.com

Regards,
AdsJumbo Team
