### ISSUE TITLE
Banner ads: OnAdRefreshed, OnErrorOccured, NoAds event

### ISSUE THREAD

**Issue by pubtom** [AdsJumbo/AdsJumbo.com#8]
Would be nice to have an OnAdRefreshed event when a new(or the first) Banner ad diplayed.

Also please add OnErrorOccured with NoAds event(s) to Banner ads..

**Comment by TiMeJuMp** [comment]
Any update on this? This is necessary for my application, to switch in the next 2 weeks on your Ad-Platform

**Comment by adjumbo** [comment]
Hello,

Please check the latest NuGet package, all of these events are now available, including programatically.

If you have any other issues, please let us know at: info@adsjumbo.com

Regards,
AdsJumbo Team
