### ISSUE TITLE
Interstitial ad ready

### ISSUE THREAD

**Issue by WiliamGP** [AdsJumbo/AdsJumbo.com#9]
How can I check if the interstitial ad has been loaded and is ready to be shown?

**Comment by pubtom** [comment]
Same as my problem: https://github.com/AdsJumbo/AdsJumbo.com/issues/7

**Comment by adjumbo** [comment]
Hello,

The interstitial ad caching is included when you invoke an interstitial ad. About 3 seconds when ad is loaded. This is a background process.

If you have any other issues, please let us know at: info@adsjumbo.com

Regards,
AdsJumbo Team
